# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               "Stochastic Learner"
tagline:             'The Dart Art of Machine Learning'
description:         'A collection of thoughts about machine learning and tech by <a href="https://twitter.com/tuxnguyen" target="_blank">@tuxnguyen</a>.'
url:                 'http://anhtu.github.io/'
baseurl:             'http://anhtu.github.io/'
paginate:            5
markdown:            kramdown


# About/contact
author:
  name:              Tu Nguyen
  url:               https://twitter.com/Tu_Ng_
  email:             anhtu2687@gmail.com

# Custom vars
version:             1.0.0
